FIREFOX_NIGHTLY_124_END = "49da40c543bd94b50675f107f6c029cfe9383570"
FIREFOX_NIGHTLY_125_END = "e41be1e61b11e44df25beae413ad0e05c04970ac"
FIREFOX_NIGHTLY_126_END = "c29594635e4bcbc06342e96df3ca3fdf84d55a0d"
FIREFOX_NIGHTLY_127_END = "23a1ac866ac4c1f5366979c94c65d0717f73591c"
FIREFOX_NIGHTLY_128_END = "d77da4d11c07b3733c674ee0abea26ef6df32643"
FIREFOX_NIGHTLY_129_END = "2c875ef12593121d0d0d565e8cec87022f659e34"
FIREFOX_NIGHTLY_130_END = "306386a9fd12553b42d65503f11374421d2ab613"
FIREFOX_NIGHTLY_131_END = "7115d9e36288b223319f7b41165f0af7db550d5a"
FIREFOX_NIGHTLY_132_END = "47dffde2ab1744f56b18e11023dac58fc9d5ea30"
FIREFOX_NIGHTLY_133_END = "7229af9311c28a1d444e56bdf645a69739bce39a"
FIREFOX_NIGHTLY_134_END = "6dc8c27d672fef50efdad840a5f4c5ac4cbe36dd"
FIREFOX_NIGHTLY_135_END = "0413c44a53cc7e5baab7c02e45498f618d57cd9c"
FIREFOX_NIGHTLY_136_END = "0b2817dd8028e8e4626fb335aeef9e009b473532"
FIREFOX_NIGHTLY_137_END = "52ef5c2d179e974e91971e6997127a1b1d1d051c"
FIREFOX_NIGHTLY_138_END = "7ccb68f5e0f4657561fddf5af6a0bad64d2e4bdc"
